# Generated by Django 5.2.3 on 2025-08-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
