# Generated by Django 5.2.3 on 2025-08-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labspaces', '0002_lab_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
