# Generated by Django 5.2.3 on 2025-08-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labspaces', '0003_lab_contact_email_lab_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('researcher', 'Researcher'), ('guest', 'Guest')], max_length=64),
        ),
    ]
