# Generated by Django 5.2.3 on 2025-08-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labspaces', '0004_alter_labmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmembership',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending'), ('owner', 'Owner'), ('manager', 'Manager'), ('researcher', 'Researcher'), ('guest', 'Guest')], max_length=64),
        ),
    ]
