# Generated by Django 5.2.3 on 2025-08-22 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labspaces', '0005_alter_labmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labmembership',
            unique_together={('lab', 'user')},
        ),
    ]
