# Generated by Django 5.2.3 on 2025-09-03 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labspaces', '0006_alter_labmembership_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labspaces.lab')),
            ],
            options={
                'unique_together': {('lab', 'name')},
            },
        ),
    ]
