# Generated by Django 5.2.3 on 2025-09-03 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labspaces', '0008_role_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='labmembership',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='labspaces.role'),
        ),
    ]
