# Generated by Django 5.2.3 on 2025-09-03 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labspaces', '0009_remove_role_display_name_alter_labmembership_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='role',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labspaces.lab'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('lab', 'name', 'is_default')},
        ),
    ]
