# Generated by Django 5.2.3 on 2025-09-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101)),
                ('category', models.CharField(choices=[('general', 'General Lab Equipment'), ('glassware', 'Glassware & Plastics'), ('chemicals', 'Chemicals & Reagents'), ('consumables', 'Consumables'), ('electronics', 'Electronics & Instruments'), ('safety', 'Safety & Storage'), ('office', 'Office & Miscellaneous'), ('other', 'Other')], default='other', max_length=64)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('broken', 'Broken')], default='available', max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
